const product_list = [
  {
    id: "배쓰",
    info: [
      {
        product_name: "오랑우탄",
        img: "./images/product_images/bath/bath01-removebg-preview.png",
        explanation: "#배쓰밤 #SOS #오랑우탄",
        price: "￦ 16,000",
      },
      {
        product_name: "럭스",
        img: "./images/product_images/bath/bath02-removebg-preview.png",
        explanation: "#배쓰밤 #럭셔리",
        price: "￦ 20,000",
      },
      {
        product_name: "레이크스",
        img: "./images/product_images/bath/bath03-removebg-preview.png",
        explanation: "#배쓰밤 #자연이떠오르는",
        price: "￦ 17,000",
      },
      {
        product_name: "블랙 로즈",
        img: "./images/product_images/bath/bath04-removebg-preview.png",
        explanation: "#배쓰밤 #화려그자체",
        price: "￦ 18,000",
      },
      {
        product_name: "다이아몬드 더스트",
        img: "./images/product_images/bath/bath05-removebg-preview.png",
        explanation: "#배쓰밤 #화려한소용돌이",
        price: "￦ 21,000",
      },
      {
        product_name: "유니콘 푸프",
        img: "./images/product_images/bath/bath06-removebg-preview.png",
        explanation: "#배쓰밤 #신비로운유니콘",
        price: "￦ 18,000",
      },
      {
        product_name: "토비스 매직 카우",
        img: "./images/product_images/bath/bath07-removebg-preview.png",
        explanation: "#배쓰밤 #고객의메시지",
        price: "￦ 13,000",
      },
      {
        product_name: "킵 잇 플러피 퍼품 버블 보틀",
        img: "./images/product_images/bath/bath08-removebg-preview.png",
        explanation: "#버블보틀 #감미로운힐링아이템",
        price: "￦ 28,000",
      },
    ],
  },
  {
    id: "샤워",
    info: [
      {
        product_name: "오렌지 330g/665g",
        img: "./images/product_images/shower/shower01-removebg-preview.png",
        explanation: "#샤워스크럽 #갓짜낸오렌지주스",
        price: "￦ 30,000",
      },
      {
        product_name: "팅글 225g",
        img: "./images/product_images/shower/shower02-removebg-preview.png",
        explanation: "#보디컨디셔너 #오감을깨우는페퍼민트",
        price: "￦ 44,000",
      },
      {
        product_name: "로즈 아르간 보디 컨디셔너 225g/450g",
        img: "./images/product_images/shower/shower03-removebg-preview.png",
        explanation: "#보디컨디셔너 #장미꽃밭에누은듯",
        price: "￦ 44,000",
      },
      {
        product_name: "매직 크리스탈스 300g/600g",
        img: "./images/product_images/shower/shower04-removebg-preview.png",
        explanation: "#스크럽 #민트의마법 #시원해져라",
        price: "￦ 30,000",
      },
      {
        product_name: "럽 럽 럽 300g/600g",
        img: "./images/product_images/shower/shower06-removebg-preview.png",
        explanation: "#샤워스크럽 #구석구석소금롤링",
        price: "￦ 30,000",
      },
      {
        product_name: "로즈 아르간",
        img: "./images/product_images/shower/shower06-removebg-preview.png",
        explanation: "#네이키드보디컨디셔너 #진짜장미향기",
        price: "￦ 28,000",
      },
      {
        product_name: "오션 솔트 셀프-프리저빙 120g/250g",
        img: "./images/product_images/shower/shower07-removebg-preview.png",
        explanation: "#스크럽 #신선한바닷소금",
        price: "￦ 28,000",
      },
      {
        product_name: "오션 솔트 120g/250g",
        img: "./images/product_images/shower/shower08-removebg-preview.png",
        explanation: "#스크럽 #소금의건강한에너지",
        price: "￦ 28,000",
      },
    ],
  },
  {
    id: "바디",
    info: [
      {
        product_name: "팬지",
        img: "./images/product_images/body/body01.png",
        explanation: "#보디로션 #감미로운향기",
        price: "￦ 46,000",
      },
      {
        product_name: "허벌리즘 100g/250g",
        img: "./images/product_images/body/body02.png",
        explanation: "#클렌저 #부드러운아침세안",
        price: "￦ 22,000",
      },
      {
        product_name: "슬리피 95g/225g",
        img: "./images/product_images/body/body03.png",
        explanation: "#보디로션 #라벤더의편안함",
        price: "￦ 24,000",
      },
      {
        product_name: "엔젤스 온 배어 스킨 100g/250g",
        img: "./images/product_images/body/body04.png",
        explanation: "#클렌저 #산뜻한마무리 #스크럽도함께",
        price: "￦ 22,000",
      },
      {
        product_name: "채러티 팟 45g/240g",
        img: "./images/product_images/body/body05.png",
        explanation: "#착한로션 #기부되는보디로션",
        price: "￦ 13,000",
      },
      {
        product_name: "더티 쉐이빙 크림 100g/225g",
        img: "./images/product_images/body/body06.png",
        explanation: "#쉐이빙크림 #오트밀크의촉촉함",
        price: "￦ 20,000",
      },
      {
        product_name: "렛 더 굿 타임즈 롤 100g/250g",
        img: "./images/product_images/body/body07.png",
        explanation: "#프레쉬클렌저 #팝콘향기 #촉촉피부",
        price: "￦ 22,000",
      },
      {
        product_name: "아쿠아 마리나 100g/250g",
        img: "./images/product_images/body/body08.png",
        explanation: "#프레쉬클렌저 #해초세안 #편한피부",
        price: "￦ 22,000",
      },
    ],
  },
  {
    id: "페이스",
    info: [
      {
        product_name: "마스크 오브 매그너민티 125g/315g",
        img: "./images/product_images/face/face01.png",
        explanation: "#꿀의촉촉함 #데일리팩 #민트팩",
        price: "￦ 22,000",
      },
      {
        product_name: "뷰티 슬립 125g/315g",
        img: "./images/product_images/face/face02.png",
        explanation: "#아름다움의비결 #골저스한영양 #라벤더",
        price: "￦ 30,000",
      },
      {
        product_name: "마스크 오브 매그너민티 셀프-프리저빙 125g/315g",
        img: "./images/product_images/face/face03.png",
        explanation: "#천연원재료 #더부드럽게",
        price: "￦ 22,000",
      },
      {
        product_name: "코스메틱 워리어",
        img: "./images/product_images/face/face04.png",
        explanation: "#피부야달래줄게 #입소문템 #에그프리",
        price: "￦ 25,000",
      },
      {
        product_name: "비비 씨위드",
        img: "./images/product_images/face/face05.png",
        explanation: "#장미의촉촉함 #해초팩# 건강한피부",
        price: "￦ 25,000",
      },
      {
        product_name: "챠콜",
        img: "./images/product_images/face/face06.png",
        explanation: "#유명한숯비누 #바로그제품 #맑은피부",
        price: "￦ 23,000",
      },
      {
        product_name: "카타스트로피 코스메틱",
        img: "./images/product_images/face/face07.png",
        explanation: "#블루베리의촉촉함 #슈퍼푸드블루베리",
        price: "￦ 25,000",
      },
      {
        product_name: "허벌리즘 100g/250g",
        img: "./images/product_images/face/face08.png",
        explanation: "#클렌저 #부드러운아침세안",
        price: "￦ 22,000",
      },
    ],
  },
  {
    id: "헤어",
    info: [
      {
        product_name: "대디-오 100g/250g/500g/1000g",
        img: "./images/product_images/hair/hair01.png",
        explanation: "#오래머무는잔향 #베스트샴푸",
        price: "￦ 19,000",
      },
      {
        product_name: "뉴",
        img: "./images/product_images/hair/hair02.png",
        explanation: "#착한고체샴푸 #뿌리튼튼",
        price: "￦ 19,000",
      },
      {
        product_name: "리햅 100g/250g/500g/1000g",
        img: "./images/product_images/hair/hair03.png",
        explanation: "#샴푸 #신선한파파야거품",
        price: "￦ 19,000",
      },
      {
        product_name: "아메리칸 크림 100g/240g/475g/1000g",
        img: "./images/product_images/hair/hair04.png",
        explanation: "#컨디셔너 #딸기밀크쉐이크",
        price: "￦ 18,000",
      },
      {
        product_name: "와사비 샨 쿠이 110g/300g/600g/1100g",
        img: "./images/product_images/hair/hair02.png",
        explanation: "#허브향기 #산뜻한두피클렌징",
        price: "￦ 26,000",
      },
      {
        product_name: "빅 130g/310g/640g",
        img: "./images/product_images/hair/hair06.png",
        explanation: "#소금샴푸 #풍성한볼륨",
        price: "￦ 20,000",
      },
      {
        product_name: "점핑 주니퍼",
        img: "./images/product_images/hair/hair07.png",
        explanation: "#샴푸바 #찰랑거리는머릿결",
        price: "￦ 19,000",
      },
      {
        product_name: "베가니스 100g/250g/500g",
        img: "./images/product_images/hair/hair08.png",
        explanation: "#컨디셔너 #산뜻한헤어케어",
        price: "￦ 18,000",
      },
    ],
  },
  {
    id: "메이크업",
    info: [
      {
        product_name: "이모셔널 브릴리언스",
        img: "./images/product_images/makeup/makeup01.png",
        explanation: "#페이스파우더 #호호바오일의부드러움",
        price: "￦ 32,000",
      },
      {
        product_name: "러쉬 래쉬스",
        img: "./images/product_images/makeup/makeup02.png",
        explanation: "#마스카라 #섬세한메이크업",
        price: "￦ 36,000",
      },
      {
        product_name: "슬랩 스틱 7C",
        img: "./images/product_images/makeup/makeup03.png",
        explanation: "#고체파운데이션 #비건뷰티",
        price: "￦ 34,000",
      },
      {
        product_name: "슬랩 스틱 5N",
        img: "./images/product_images/makeup/makeup04.png",
        explanation: "#고체파운데이션 #비건뷰티",
        price: "￦ 34,000",
      },
      {
        product_name: "독립",
        img: "./images/product_images/makeup/makeup05.png",
        explanation: "#리퀴드아이라이너 #오늘도위풍당당하게",
        price: "￦ 35,000",
      },
      {
        product_name: "슬랩 스틱 11N",
        img: "./images/product_images/makeup/makeup06.png",
        explanation: "#고체파운데이션 #비건뷰티",
        price: "￦ 34,000",
      },
      {
        product_name: "슬랩 스틱 1C",
        img: "./images/product_images/makeup/makeup07.png",
        explanation: "#고체파운데이션 #비건뷰티",
        price: "￦ 34,000",
      },
      {
        product_name: "슬랩 스틱 4C",
        img: "./images/product_images/makeup/makeup08.png",
        explanation: "#고체파운데이션 #비건뷰티",
        price: "￦ 34,000",
      },
    ],
  },
  {
    id: "퍼퓸",
    info: [
      {
        product_name: "빅",
        img: "./images/product_images/perfume/perfume01.png",
        explanation: "#보디스프레이 #우아한네롤리",
        price: "￦ 70,000",
      },
      {
        product_name: "섹스 밤",
        img: "./images/product_images/perfume/perfume02.png",
        explanation: "#보디스프레이 #은은한자스민",
        price: "￦ 60,000",
      },
      {
        product_name: "제스티",
        img: "./images/product_images/perfume/perfume03.png",
        explanation: "#보디스프레이 #상큼한라임",
        price: "￦ 60,000",
      },
      {
        product_name: "솔티",
        img: "./images/product_images/perfume/perfume04.png",
        explanation: "#보디스프레이 #해변가로의여행",
        price: "￦ 80,000",
      },
      {
        product_name: "더 컴포터",
        img: "./images/product_images/perfume/perfume05.png",
        explanation: "#보디스프레이 #달콤한향기",
        price: "￦ 60,000",
      },
      {
        product_name: "더티 보디 스프레이",
        img: "./images/product_images/perfume/perfume06.png",
        explanation: "#스테디셀러 #뒤돌아보는향 #재구매각",
        price: "￦ 60,000",
      },
      {
        product_name: "트와일라잇",
        img: "./images/product_images/perfume/perfume07.png",
        explanation: "#보디스프레이 #차분한달콤함",
        price: "￦ 60,000",
      },
      {
        product_name: "대드스 가든 레몬 트리",
        img: "./images/product_images/perfume/perfume08.png",
        explanation: "#보디스프레이 #레몬라임상큼짜릿",
        price: "￦ 60,000",
      },
    ],
  },
];
